spring.application.name=demo



spring.datasource.url=jdbc:postgresql://ep-crimson-truth-a1zsv7ew-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_rMKNvH7laEp0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.data-source-properties.sslmode=require