# Use Java 17
FROM eclipse-temurin:17-jdk

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Build the project
RUN chmod +x mvnw && ./mvnw clean package -DskipTests

# Rename jar to fixed name
RUN cp target/*.jar app.jar

# Run the application
CMD ["java", "-jar", "app.jar"]